name: Deploy to Production

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Check if the branch is production
    - name: Ensure the branch is production
      run: |
        if [ "${{ github.ref_name }}" != "production" ]; then
          echo "This workflow can only be run on the production branch."
          exit 1
        fi
    
    # Build and run Docker Compose
    - name: Build and Test Docker Compose
      run: |
        docker compose build
        docker compose up -d
        docker compose ps
      env:
        DOCKER_BUILDKIT: 1

    # Install SSH Client
    - name: Install SSH Client
      run: sudo apt-get update && sudo apt-get install -y sshpass

    # Deploy to VPS Server via bash
    - name: SSH and Run Command on VPS
      env:
        SSH_USER: ${{ secrets.VPS_USER }}
        SSH_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        VPS_IP: ${{ secrets.VPS_IP }}
      run: |
        sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no "$SSH_USER@$VPS_IP" 'bash -i -c "karczrun"'
